### PR TITLE
Hello world

### PR DESCRIPTION
**Pull request by ranandnair**

### CODE REVIEW

**Comment by aragavendran** [comment]
1. Can you move main.rs to a new folder?
2. can you add executable to .giignore file?

**Comment by aragavendran** [comment]
- i still see main.rs in the root dir
- `main` executable is not added to the .gitignore

**Comment by ranandnair** [comment]
> * Can you move main.rs to a new folder? -- This is taken care 
> * can you add executable to .giignore file? -- This has been added 


> * i still see main.rs in the root dir. -- Done
> * `main` executable is not added to the .gitignore -- Updated it this time

**Comment by aragavendran** [comment]
@ranandnair can you re-open the PR?

**Comment by ranandnair** [comment]
> @ranandnair can you re-open the PR?

I have reopened it

**Pull request merged**
